### ISSUE TITLE
make compile error

### ISSUE THREAD

**Issue by ea42gh** [sisl/tufte_algorithms_book#21]
I had never used PythonTex before. `make compile` results in
```
 PythonTeX error
    The version of the PythonTeX scripts does not match the last code
    saved by the document--run LaTeX to create an updated version.
```
searching the web did not help. How would one fix this?

**Comment by tawheeler** [comment]
What version of pythontex do you have installed? This repo uses v0.17.

You can try running just the subset of the makefile command to see your what it does with each command:
```
-julia --color=yes pull_julia_code.jl
lualatex book
pythontex book
biber book
lualatex book
```
Chances are that the pythontex command is failing.

**Comment by ea42gh** [comment]
I had: the error comes from pythontex 0.16
Installing pythontex 0.17 resolved the problem, thank you1

**Comment by johnnychen94** [comment]
The pythontex.sty file in this repository needs to be updated accordingly, you can find the workaround from #19 and #20
