### ISSUE TITLE
Work in new table of contents format

### ISSUE THREAD

**Issue by mykelk** [sisl/tufte_algorithms_book#29]
@tawheeler greatly improved the appearance of the TOC as part of the new Algorithms for Decision Making book. It would be good to get this merged in here.

**Comment by tawheeler** [comment]
The new TOC is specific to books that use parts. I'm not sure most books do that.

**Comment by mykelk** [comment]
True. Yeah, perhaps most books won't have parts. Though I think the styling of your chapter / section headings in the TOC is still an upgrade from what is there is currently.
