### ISSUE TITLE
Additional Dependencies

### ISSUE THREAD

**Issue by BeastyBlacksmith** [sisl/tufte_algorithms_book#7]
I found that you also need to `add Colors`.

**Comment by tawheeler** [comment]
Good point - `Colors` is in the REQUIRE file but the install instructions only have you install Weave and PGFPlots.jl. I updated the README in 3d33ac6.
Please try that out. If it works, close the issue, and if not, please post so we can fix it :)

**Comment by BeastyBlacksmith** [comment]
That works.
